apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      component: kafka-manager
  template:
    metadata:
      labels:
        component: kafka-manager
    spec:
      containers:
        - image: hlebalbau/kafka-manager:stable
          name: kafka-manager
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
          env:
            - name: ZK_HOSTS
              value: "zookeeper-cluster-ip-service:2181"
            - name: APPLICATION_SECRET
              value: "random-secret"
            - name: KAFKA_MANAGER_AUTH_ENABLED
              value: "true"
            - name: KAFKA_MANAGER_USERNAME
              value: "root"
            - name: KAFKA_MANAGER_PASSWORD
              value: "root"
          ports:
            - containerPort: 9000
              name: kafka-manager
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
