apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      component: zookeeper
  template:
    metadata:
      labels:
        component: zookeeper
    spec:
      containers:
        - image: bitnami/zookeeper
          name: zookeeper
          resources:              
            requests:
              cpu: "20m"
              memory: "55M"
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
              name: zookeeper
          livenessProbe:
            exec:
              command:
                [
                  "/bin/bash",
                  "-c",
                  'echo "srvr" | nc -w 2 -q 2 localhost 2181 | grep Received',
                ]
            initialDelaySeconds: 15
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command:
                [
                  "/bin/bash",
                  "-c",
                  'echo "srvr" | nc -w 2 -q 2 localhost 2181 | grep Received',
                ]
            initialDelaySeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /bitnami/zookeeper
              name: zookeeper-storage
      volumes:
        - name: zookeeper-storage
          persistentVolumeClaim:
            claimName: kafka-persistance-volume-claim
