apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      component: consumer
  template:
    metadata:
      labels:
        component: consumer
    spec:
      containers:
        - image: adminer
          name: consumer
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 8300
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 8300
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: KAFKA_HOST
              value: 'kafka01:9092'
            - name: DB_HOST
              value: 'db-service:3306'  
          ports:
            - containerPort: 8300
              name: consumer
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
