apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      component: producer
  template:
    metadata:
      labels:
        component: producer
    spec:
      containers:
        - image: adminer
          name: producer
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 8200
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 8200
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: KAFKA_HOST
              value: 'kafka01:9092'
          ports:
            - containerPort: 8200
              name: producer
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
