version: '3.1'

services:
  zookeeper:
    container_name: zookeeper       
    image: 'bitnami/zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - '/home/majid/Documents/Study/Kafka/tutorial/volumes/zookeeper-data:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
  kafka01:
    container_name: kafka01
    image: 'bitnami/kafka'
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - '/home/majid/Documents/Study/Kafka/tutorial/volumes/kafka-data:/bitnami/kafka'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka01:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
    networks:
      - app-tier
  kafka_manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: root
      KAFKA_MANAGER_PASSWORD: root
    depends_on:
      - zookeeper
    command: -Dpidfile.path=/dev/null  
    networks:
      - app-tier   

networks:
  app-tier:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
