apiVersion: v1
kind: ConfigMap
metadata:
  name: envread-settings
  # namespace: production
data:
  config.json: |-
    {
      "producerUrl": "http://192.168.99.100/api/producer/order/",
      "consumerUrl": "http://192.168.99.100/api/consumer/order/"
    }
