apiVersion: v1
kind: ConfigMap
metadata:
  name: envread-settings
  # namespace: production
  # set 192.168.99.102 to your minikub id on Cloud platform generate a static ip
data:
  config.json: |-
    {
      "producerUrl": "http://192.168.99.102/api/producer/order/",
      "consumerUrl": "http://192.168.99.102/api/consumer/order/"
    }
