apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      component: food-app
  template:
    metadata:
      labels:
        component: food-app
    spec:
      containers:
        - image: majidshaikh16/food-app:v2
          name: food-app
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
          # livenessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 80
          #   initialDelaySeconds: 90
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /_status/healthz
          #     port: 80
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10 
          ports:
            - containerPort: 80
              name: food-app
          volumeMounts:
            - mountPath: /usr/share/nginx/html/food-app/assets/
              name: data
      volumes:
        - name: data
          configMap:
            name: envread-settings
          
